cultura:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DB_DW_HOST_CULTURA') }}"
      port: "{{ env_var('DB_DW_PORT_CULTURA') | int }}"
      user: "{{ env_var('DB_DW_USER_CULTURA') }}"
      password: "{{ env_var('DB_DW_PASS_CULTURA') }}"
      dbname: "{{ env_var('DB_DW_DATABASE_CULTURA') }}"
      schema: "{{ env_var('DB_DW_SCHEMA_CULTURA', 'cultura') }}"
      threads: 4
