cultura:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DB_DW_HOST_CULTURA', 'dummy_host') }}"
      port: "{{ env_var('DB_DW_PORT_CULTURA', '5432') | int }}"
      user: "{{ env_var('DB_DW_USER_CULTURA', 'dummy_user') }}"
      password: "{{ env_var('DB_DW_PASS_CULTURA', 'dummy_pass') }}"
      dbname: "{{ env_var('DB_DW_DATABASE_CULTURA', 'dummy_db') }}"
      schema: "{{ env_var('DB_DW_SCHEMA_CULTURA', 'cultura') }}"
      threads: 4