-- Bronze SALIC — sac__vwpainelpareceristaunificado.
-- Origem: salic_bronze.sac__vwpainelpareceristaunificado, onde tudo chega como texto da
-- ingestão via Trino (ADR 0005). Tipar é o trabalho desta camada.
-- 60 colunas: 23 tipadas, 36 mantidas como texto.
-- Os casts são guardados por regex (macros bronze_*): valor fora do
-- padrão vira NULL em vez de derrubar o modelo.
select
    {{ bronze_texto("tipopainel") }} as tipopainel,
    {{ bronze_inteiro("idpronac") }} as idpronac,
    {{ bronze_inteiro("pronac") }} as pronac,
    {{ bronze_texto("nomeprojeto") }} as nomeprojeto,
    {{ bronze_texto("dtanalise") }} as dtanalise,
    {{ bronze_texto("situacao") }} as situacao,
    {{ bronze_inteiro("idorgao") }} as idorgao,
    {{ bronze_texto("orgaosigla") }} as orgaosigla,
    {{ bronze_timestamp("dtsolicitacao") }} as dtsolicitacao,
    {{ bronze_timestamp("dtresposta") }} as dtresposta,
    {{ bronze_texto("stenviado") }} as stenviado,
    {{ bronze_inteiro("quantidadeprodutos") }} as quantidadeprodutos,
    {{ bronze_inteiro("idprojeto") }} as idprojeto,
    {{ bronze_inteiro("iddistribuirparecer") }} as iddistribuirparecer,
    {{ bronze_inteiro("idproduto") }} as idproduto,
    {{ bronze_texto("stprincipal") }} as stprincipal,
    {{ bronze_texto("tipoanalise") }} as tipoanalise,
    {{ bronze_timestamp("dtdistribuicao") }} as dtdistribuicao,
    {{ bronze_texto("stdiligenciado") }} as stdiligenciado,
    {{ bronze_texto("dtdevolucao") }} as dtdevolucao,
    {{ bronze_timestamp("dtenvio") }} as dtenvio,
    {{ bronze_texto("fecharanalise") }} as fecharanalise,
    {{ bronze_inteiro("sianalise") }} as sianalise,
    {{ bronze_inteiro("idorgaoorigem") }} as idorgaoorigem,
    {{ bronze_texto("tpreadequacao") }} as tpreadequacao,
    {{ bronze_texto("dstiporeadequacao") }} as dstiporeadequacao,
    {{ bronze_inteiro("qtdiasavaliacao") }} as qtdiasavaliacao,
    {{ bronze_inteiro("idtecnicoparecerista") }} as idtecnicoparecerista,
    {{ bronze_inteiro("idorgaounidade") }} as idorgaounidade,
    {{ bronze_inteiro("idreadequacao") }} as idreadequacao,
    {{ bronze_inteiro("iddocumento") }} as iddocumento,
    {{ bronze_texto("siencaminhamento") }} as siencaminhamento,
    {{ bronze_texto("stanalise") }} as stanalise,
    {{ bronze_texto("idnrreuniao") }} as idnrreuniao,
    {{ bronze_texto("stestado") }} as stestado,
    {{ bronze_inteiro("idsolicitante") }} as idsolicitante,
    {{ bronze_inteiro("idavaliador") }} as idavaliador,
    {{ bronze_texto("statendimento") }} as statendimento,
    {{ bronze_inteiro("idtiporeadequacao") }} as idtiporeadequacao,
    {{ bronze_texto("dssolicitacao") }} as dssolicitacao,
    {{ bronze_texto("dsjustificativa") }} as dsjustificativa,
    {{ bronze_texto("dsavaliacao") }} as dsavaliacao,
    {{ bronze_texto("dsorientacao") }} as dsorientacao,
    {{ bronze_texto("dsnomesolicitante") }} as dsnomesolicitante,
    {{ bronze_texto("dsnomeavaliador") }} as dsnomeavaliador,
    {{ bronze_texto("iddocumentoassinatura") }} as iddocumentoassinatura,
    {{ bronze_texto("idtipodoatoadministrativo") }} as idtipodoatoadministrativo,
    {{ bronze_texto("dsproduto") }} as dsproduto,
    {{ bronze_texto("nomeproduto") }} as nomeproduto,
    {{ bronze_texto("tempofimdiligencia") }} as tempofimdiligencia,
    {{ bronze_inteiro("idavaliadordistribuicao") }} as idavaliadordistribuicao,
    {{ bronze_inteiro("idagenteparecerista") }} as idagenteparecerista,
    {{ bronze_texto("iddistribuirprojeto") }} as iddistribuirprojeto,
    {{ bronze_texto("dssolicitacaorecurso") }} as dssolicitacaorecurso,
    {{ bronze_texto("idrecurso") }} as idrecurso,
    {{ bronze_texto("tprecurso") }} as tprecurso,
    {{ bronze_texto("sedisponivelassinatura") }} as sedisponivelassinatura,
    {{ bronze_texto("sediligenciaaberta") }} as sediligenciaaberta,
    {{ bronze_texto("sirecurso") }} as sirecurso,
    _fatia
from {{ source("bronze_sac", "sac__vwpainelpareceristaunificado") }}
