-- Bronze SALIC — sac__preprojeto.
-- Origem: salic_bronze.sac__preprojeto, onde tudo chega como texto da ingestão
-- via Trino (ADR 0005). Tipar é o trabalho desta camada.
-- 36 colunas de negócio + _fatia. Os campos longos (justificativa, objetivos,
-- sinopse, ficha técnica...) guardam HTML da origem e ficam TEXT sem limpeza.
-- Datas e flags são convertidas por regex; o resto fica TEXT.
select
    {{ bronze_inteiro("idpreprojeto") }} as idpreprojeto,
    {{ bronze_inteiro("idagente") }} as idagente,
    {{ bronze_texto("nomeprojeto") }} as nomeprojeto,
    {{ bronze_inteiro("mecanismo") }} as mecanismo,
    {{ bronze_texto("agenciabancaria") }} as agenciabancaria,
    {{ bronze_booleano("areaabrangencia") }} as areaabrangencia,
    {{ bronze_timestamp("dtiniciodeexecucao") }} as dtiniciodeexecucao,
    {{ bronze_timestamp("dtfinaldeexecucao") }} as dtfinaldeexecucao,
    {{ bronze_texto("justificativa") }} as justificativa,
    {{ bronze_inteiro("nratotombamento") }} as nratotombamento,
    {{ bronze_timestamp("dtatotombamento") }} as dtatotombamento,
    {{ bronze_inteiro("esferatombamento") }} as esferatombamento,
    {{ bronze_texto("resumodoprojeto") }} as resumodoprojeto,
    {{ bronze_texto("objetivos") }} as objetivos,
    {{ bronze_texto("acessibilidade") }} as acessibilidade,
    {{ bronze_texto("democratizacaodeacesso") }} as democratizacaodeacesso,
    {{ bronze_texto("etapadetrabalho") }} as etapadetrabalho,
    {{ bronze_texto("fichatecnica") }} as fichatecnica,
    {{ bronze_texto("sinopse") }} as sinopse,
    {{ bronze_texto("impactoambiental") }} as impactoambiental,
    {{ bronze_texto("especificacaotecnica") }} as especificacaotecnica,
    {{ bronze_texto("estrategiadeexecucao") }} as estrategiadeexecucao,
    {{ bronze_timestamp("dtaceite") }} as dtaceite,
    {{ bronze_timestamp("dtarquivamento") }} as dtarquivamento,
    {{ bronze_booleano("stestado") }} as stestado,
    {{ bronze_booleano("stdatafixa") }} as stdatafixa,
    {{ bronze_booleano("stplanoanual") }} as stplanoanual,
    {{ bronze_inteiro("idusuario") }} as idusuario,
    {{ bronze_texto("sttipodemanda") }} as sttipodemanda,
    {{ bronze_inteiro("idedital") }} as idedital,
    {{ bronze_inteiro("stproposta") }} as stproposta,
    {{ bronze_booleano("tpprorrogacao") }} as tpprorrogacao,
    {{ bronze_texto("descricaoatividade") }} as descricaoatividade,
    {{ bronze_inteiro("tptipicidade") }} as tptipicidade,
    {{ bronze_inteiro("tptipologia") }} as tptipologia,
    {{ bronze_texto("idpronaccontinuacao") }} as idpronaccontinuacao,
    _fatia
from {{ source("bronze_sac", "sac__preprojeto") }}
