-- Bronze SALIC — sac__acompanhamentobandasx.
-- Origem: salic_bronze.sac__acompanhamentobandasx, onde tudo chega como texto da
-- ingestão via Trino (ADR 0005). Tipar é o trabalho desta camada.
-- 64 colunas: 57 tipadas, 6 mantidas como texto.
-- Os casts são guardados por regex (macros bronze_*): valor fora do
-- padrão vira NULL em vez de derrubar o modelo.
select
    {{ bronze_texto("anoprojeto") }} as anoprojeto,
    {{ bronze_texto("sequencial") }} as sequencial,
    {{ bronze_texto("instituicao") }} as instituicao,
    {{ bronze_booleano("campo07") }} as campo07,
    {{ bronze_booleano("campo08") }} as campo08,
    {{ bronze_inteiro("campo09b") }} as campo09b,
    {{ bronze_inteiro("campo09c") }} as campo09c,
    {{ bronze_inteiro("campo10a") }} as campo10a,
    {{ bronze_inteiro("campo10b") }} as campo10b,
    {{ bronze_inteiro("campo10c") }} as campo10c,
    {{ bronze_inteiro("campo10d") }} as campo10d,
    {{ bronze_booleano("campo11a") }} as campo11a,
    {{ bronze_booleano("campo11b") }} as campo11b,
    {{ bronze_booleano("campo11c") }} as campo11c,
    {{ bronze_booleano("campo11d") }} as campo11d,
    {{ bronze_booleano("campo11e") }} as campo11e,
    {{ bronze_inteiro("campo13") }} as campo13,
    {{ bronze_booleano("campo14") }} as campo14,
    {{ bronze_booleano("campo15") }} as campo15,
    {{ bronze_booleano("campo16") }} as campo16,
    {{ bronze_booleano("campo17") }} as campo17,
    {{ bronze_booleano("campo18") }} as campo18,
    {{ bronze_inteiro("campo19a") }} as campo19a,
    {{ bronze_inteiro("campo19b") }} as campo19b,
    {{ bronze_inteiro("campo19c") }} as campo19c,
    {{ bronze_inteiro("campo19d") }} as campo19d,
    {{ bronze_booleano("campo20a") }} as campo20a,
    {{ bronze_booleano("campo20b") }} as campo20b,
    {{ bronze_booleano("campo20c") }} as campo20c,
    {{ bronze_booleano("campo20d") }} as campo20d,
    {{ bronze_booleano("campo20e") }} as campo20e,
    {{ bronze_booleano("campo20f") }} as campo20f,
    {{ bronze_booleano("campo20g") }} as campo20g,
    {{ bronze_booleano("campo20h") }} as campo20h,
    {{ bronze_booleano("campo21") }} as campo21,
    {{ bronze_booleano("campo22") }} as campo22,
    {{ bronze_booleano("campo23") }} as campo23,
    {{ bronze_booleano("campo24") }} as campo24,
    {{ bronze_booleano("campo25a") }} as campo25a,
    {{ bronze_booleano("campo25b") }} as campo25b,
    {{ bronze_booleano("campo26") }} as campo26,
    {{ bronze_inteiro("campo27a") }} as campo27a,
    {{ bronze_inteiro("campo27b") }} as campo27b,
    {{ bronze_inteiro("campo27c") }} as campo27c,
    {{ bronze_inteiro("campo27d") }} as campo27d,
    {{ bronze_inteiro("campo27e") }} as campo27e,
    {{ bronze_inteiro("campo27f") }} as campo27f,
    {{ bronze_inteiro("campo27g") }} as campo27g,
    {{ bronze_inteiro("campo27h") }} as campo27h,
    {{ bronze_booleano("campo29a") }} as campo29a,
    {{ bronze_booleano("campo29b") }} as campo29b,
    {{ bronze_booleano("campo29c") }} as campo29c,
    {{ bronze_booleano("campo29d") }} as campo29d,
    {{ bronze_booleano("campo29e") }} as campo29e,
    {{ bronze_booleano("campo30a") }} as campo30a,
    {{ bronze_booleano("campo30b") }} as campo30b,
    {{ bronze_booleano("campo30c") }} as campo30c,
    {{ bronze_booleano("campo30d") }} as campo30d,
    {{ bronze_inteiro("logon") }} as logon,
    {{ bronze_texto("responsavelbanda") }} as responsavelbanda,
    {{ bronze_texto("maestrobanda") }} as maestrobanda,
    {{ bronze_texto("formacaomaestro") }} as formacaomaestro,
    {{ bronze_booleano("auditadasfci") }} as auditadasfci,
    _fatia
from {{ source("bronze_sac", "sac__acompanhamentobandasx") }}
