name: 'cultura'

version: 1.0.0
config-version: 2

profile: cultura

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  cultura:
    metadata:
      +materialized: incremental
      +schema: metadata
    agentes_dbt:
      +materialized: table
      +schema: agentes
      bronze:
        +materialized: incremental
      views:
        +materialized: view
