-- Bronze transferegov — plano_acao_minc.
-- Origem: transferegov.plano_acao_minc, onde tudo chega como text da ingestão via API.
-- Tipar é o trabalho desta camada.
-- 56 colunas: 19 tipadas, 37 mantidas como texto.
-- O cast vem do padrão medido no dado (scripts/perfilar_padroes.py),
-- não do nome da coluna: exige 100% dos valores preenchidos casando.
select
    {{ bronze_inteiro("id_plano_acao") }} as id_plano_acao,
    {{ bronze_texto("codigo_plano_acao") }} as codigo_plano_acao,
    {{ bronze_data("data_inicio_vigencia_plano_acao") }} as data_inicio_vigencia_plano_acao,
    {{ bronze_data("data_fim_vigencia_plano_acao") }} as data_fim_vigencia_plano_acao,
    {{ bronze_texto("diagnostico_plano_acao") }} as diagnostico_plano_acao,
    {{ bronze_texto("objetivos_plano_acao") }} as objetivos_plano_acao,
    {{ bronze_texto("situacao_plano_acao") }} as situacao_plano_acao,
    {{ bronze_texto("valor_repasse_emenda_plano_acao") }} as valor_repasse_emenda_plano_acao,
    {{ bronze_numerico("valor_repasse_especifico_plano_acao") }} as valor_repasse_especifico_plano_acao,
    {{ bronze_texto("valor_repasse_voluntario_plano_acao") }} as valor_repasse_voluntario_plano_acao,
    {{ bronze_numerico("valor_total_repasse_plano_acao") }} as valor_total_repasse_plano_acao,
    {{ bronze_numerico("valor_recursos_proprios_plano_acao") }} as valor_recursos_proprios_plano_acao,
    {{ bronze_numerico("valor_outros_plano_acao") }} as valor_outros_plano_acao,
    {{ bronze_numerico("valor_rendimentos_aplicacao_plano_acao") }} as valor_rendimentos_aplicacao_plano_acao,
    {{ bronze_numerico("valor_total_plano_acao") }} as valor_total_plano_acao,
    {{ bronze_texto("valor_total_investimento_plano_acao") }} as valor_total_investimento_plano_acao,
    {{ bronze_numerico("valor_total_custeio_plano_acao") }} as valor_total_custeio_plano_acao,
    {{ bronze_numerico("valor_saldo_disponivel_plano_acao") }} as valor_saldo_disponivel_plano_acao,
    {{ bronze_texto("id_orgao_repassador_plano_acao") }} as id_orgao_repassador_plano_acao,
    {{ bronze_texto("sigla_orgao_repassador_plano_acao") }} as sigla_orgao_repassador_plano_acao,
    {{ bronze_texto("cnpj_orgao_repassador_plano_acao") }} as cnpj_orgao_repassador_plano_acao,
    {{ bronze_texto("nome_orgao_repassador_plano_acao") }} as nome_orgao_repassador_plano_acao,
    {{ bronze_texto("id_ente_repassador_plano_acao") }} as id_ente_repassador_plano_acao,
    {{ bronze_texto("cnpj_ente_repassador_plano_acao") }} as cnpj_ente_repassador_plano_acao,
    {{ bronze_texto("nome_ente_repassador_plano_acao") }} as nome_ente_repassador_plano_acao,
    {{ bronze_texto("uf_ente_repassador_plano_acao") }} as uf_ente_repassador_plano_acao,
    {{ bronze_texto("nome_municipio_ente_repassador_plano_acao") }} as nome_municipio_ente_repassador_plano_acao,
    {{ bronze_texto("codigo_ibge_municipio_ente_repassador_plano_acao") }} as codigo_ibge_municipio_ente_repassador_plano_acao,
    {{ bronze_inteiro("id_ente_recebedor_plano_acao") }} as id_ente_recebedor_plano_acao,
    {{ bronze_texto("cnpj_ente_recebedor_plano_acao") }} as cnpj_ente_recebedor_plano_acao,
    {{ bronze_texto("nome_ente_recebedor_plano_acao") }} as nome_ente_recebedor_plano_acao,
    {{ bronze_texto("uf_ente_recebedor_plano_acao") }} as uf_ente_recebedor_plano_acao,
    {{ bronze_texto("nome_municipio_ente_recebedor_plano_acao") }} as nome_municipio_ente_recebedor_plano_acao,
    {{ bronze_inteiro("codigo_ibge_municipio_ente_recebedor_plano_acao") }} as codigo_ibge_municipio_ente_recebedor_plano_acao,
    {{ bronze_texto("tipo_unidade_recebedora_plano_acao") }} as tipo_unidade_recebedora_plano_acao,
    {{ bronze_texto("descricao_tipo_unidade_ente_plano_acao") }} as descricao_tipo_unidade_ente_plano_acao,
    {{ bronze_inteiro("id_fundo_repassador_plano_acao") }} as id_fundo_repassador_plano_acao,
    {{ bronze_texto("cnpj_fundo_repassador_plano_acao") }} as cnpj_fundo_repassador_plano_acao,
    {{ bronze_texto("nome_fundo_repassador_plano_acao") }} as nome_fundo_repassador_plano_acao,
    {{ bronze_texto("uf_fundo_repassador_plano_acao") }} as uf_fundo_repassador_plano_acao,
    {{ bronze_texto("municipio_fundo_repassador_plano_acao") }} as municipio_fundo_repassador_plano_acao,
    {{ bronze_texto("codigo_ibge_fundo_repassador_plano_acao") }} as codigo_ibge_fundo_repassador_plano_acao,
    {{ bronze_texto("id_fundo_vinculado_plano_acao") }} as id_fundo_vinculado_plano_acao,
    {{ bronze_texto("cnpj_fundo_vinculado_plano_acao") }} as cnpj_fundo_vinculado_plano_acao,
    {{ bronze_texto("nome_fundo_vinculado_plano_acao") }} as nome_fundo_vinculado_plano_acao,
    {{ bronze_texto("uf_fundo_vinculado_plano_acao") }} as uf_fundo_vinculado_plano_acao,
    {{ bronze_texto("municipio_fundo_vinculado_plano_acao") }} as municipio_fundo_vinculado_plano_acao,
    {{ bronze_texto("codigo_ibge_fundo_vinculado_plano_acao") }} as codigo_ibge_fundo_vinculado_plano_acao,
    {{ bronze_texto("tipo_unidade_recebedora_vinculada_plano_acao") }} as tipo_unidade_recebedora_vinculada_plano_acao,
    {{ bronze_texto("descricao_tipo_unidade_recebedora_vinculada_plano_acao") }} as descricao_tipo_unidade_recebedora_vinculada_plano_acao,
    {{ bronze_inteiro("id_programa") }} as id_programa,
    {{ bronze_texto("tipo_ente") }} as tipo_ente,
    {{ bronze_inteiro("cod_ibge") }} as cod_ibge,
    {{ bronze_inteiro("cod_ibge_uf") }} as cod_ibge_uf,
    {{ bronze_inteiro("cod_ibge_municipio") }} as cod_ibge_municipio,
    {{ bronze_timestamp("dt_ingest") }} as dt_ingest
from {{ source("transferegov", "plano_acao_minc") }}
